name: 👕 Check

on:
  push:
  pull_request:


jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: wolletd/clang-format-checker@v1
        with:
          target-ref: patch-4      # required, merge target
          clang-version: 10     # optional, default: latest (in image)
          fetch-depth: 50       # optional, rarely needed, default: 50
          source-ref: HEAD      # optional, almost never needed, default: HEAD
