# Workflow syntax:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: 👕 Check

on:
  push:
  pull_request:


jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: wolletd/clang-format-checker@v1
        with:
          target-ref: master    # required, merge target
          clang-version: 12     # optional, default: latest (in image)
